import { IFood, IRestaurant as IRestaurantType } from '@/types/store';

export interface IRestaurantDetail {
  id: string;
  name: string;
  description: string;
  image: string;
  rating: number;
  deliveryFee: string;
  deliveryTime: string;
  categories: string[];
  foods: IFood[];
}

// Mock data for RestaurantCard component
export const mockRestaurants: IRestaurantType[] = [
  {
    id: '1',
    name: 'Adenine Kitchen',
    image: {
      uri: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
    },
    categories: 'Italian • Pizza • Pasta',
    rating: 4.5,
    deliveryFee: 'free',
    deliveryTime: '20-30 min',
  },
  {
    id: '2',
    name: 'Burger Palace',
    image: {
      uri: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop',
    },
    categories: 'American • Burgers • Fast Food',
    rating: 4.3,
    deliveryFee: '$2.99',
    deliveryTime: '15-25 min',
  },
  {
    id: '3',
    name: 'Sushi Master',
    image: {
      uri: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop',
    },
    categories: 'Japanese • Sushi • Asian',
    rating: 4.8,
    deliveryFee: 'free',
    deliveryTime: '25-35 min',
  },
  {
    id: '4',
    name: 'Taco Fiesta',
    image: {
      uri: 'https://plus.unsplash.com/premium_photo-1661883237884-263e8de8869b?q=80&w=1489&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    },
    categories: 'Mexican • Tacos • Spicy',
    rating: 4.6,
    deliveryFee: '$1.99',
    deliveryTime: '20-30 min',
  },
  {
    id: '5',
    name: 'Green Garden',
    image: {
      uri: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    },
    categories: 'Healthy • Salads • Vegan',
    rating: 4.4,
    deliveryFee: 'free',
    deliveryTime: '15-20 min',
  },
  {
    id: '6',
    name: 'Pizza Corner',
    image: {
      uri: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
    },
    categories: 'Italian • Pizza • Cheese',
    rating: 4.7,
    deliveryFee: '$3.50',
    deliveryTime: '30-40 min',
  },
  {
    id: '7',
    name: 'Noodle House',
    image: {
      uri: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop',
    },
    categories: 'Asian • Noodles • Soup',
    rating: 4.2,
    deliveryFee: '$2.50',
    deliveryTime: '25-35 min',
  },
  {
    id: '8',
    name: 'BBQ Station',
    image: {
      uri: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
    },
    categories: 'BBQ • Grilled • Meat',
    rating: 4.9,
    deliveryFee: 'free',
    deliveryTime: '35-45 min',
  },
];

export const mockFoodItems: IFood[] = [
  {
    id: '1',
    name: 'Burger Ferguson',
    description:
      'Delicious beef burger with fresh vegetables, Delicious beef burger with fresh vegetables',
    price: 12.99,
    image: 'food-1.png',
    category: 'Burgers',
    rating: 4.5,
    isPopular: true,
    preparationTime: '15 min',
  },
  {
    id: '2',
    name: 'Chicken Deluxe',
    description: 'Grilled chicken with special sauce',
    price: 14.5,
    image: 'food-2.png',
    category: 'Chicken',
    rating: 4.3,
    preparationTime: '20 min',
  },
  {
    id: '3',
    name: 'Spicy Pizza',
    description: 'Hot pizza with pepperoni and jalapeños',
    price: 18.99,
    image: 'food-3.png',
    category: 'Pizza',
    rating: 4.7,
    isPopular: true,
    preparationTime: '25 min',
  },
  {
    id: '4',
    name: 'Caesar Salad',
    description: 'Fresh salad with caesar dressing',
    price: 9.99,
    image: 'food-4.png',
    category: 'Salads',
    rating: 4.2,
    preparationTime: '10 min',
  },
  {
    id: '5',
    name: 'Fish & Chips',
    description: 'Crispy fish with golden fries',
    price: 16.5,
    image: 'food-5.png',
    category: 'Seafood',
    rating: 4.4,
    preparationTime: '18 min',
  },
  {
    id: '6',
    name: 'Pasta Carbonara',
    description: 'Creamy pasta with bacon and parmesan',
    price: 15.99,
    image: 'food-6.png',
    category: 'Pasta',
    rating: 4.6,
    isPopular: true,
    preparationTime: '22 min',
  },
  {
    id: '7',
    name: 'BBQ Ribs',
    description: 'Tender pork ribs with smoky BBQ sauce',
    price: 22.99,
    image: 'food-7.png',
    category: 'BBQ',
    rating: 4.8,
    isPopular: true,
    preparationTime: '35 min',
  },
  {
    id: '8',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato, mozzarella and basil',
    price: 16.99,
    image: 'food-8.png',
    category: 'Pizza',
    rating: 4.4,
    preparationTime: '20 min',
  },
  {
    id: '9',
    name: 'Chicken Wings',
    description: 'Spicy buffalo wings with blue cheese dip',
    price: 13.99,
    image: 'food-9.png',
    category: 'Chicken',
    rating: 4.3,
    preparationTime: '18 min',
  },
  {
    id: '10',
    name: 'Greek Salad',
    description: 'Fresh vegetables with feta cheese and olives',
    price: 11.99,
    image: 'food-10.png',
    category: 'Salads',
    rating: 4.1,
    preparationTime: '8 min',
  },
  {
    id: '11',
    name: 'Salmon Teriyaki',
    description: 'Grilled salmon with teriyaki glaze',
    price: 24.99,
    image: 'food-11.png',
    category: 'Seafood',
    rating: 4.7,
    isPopular: true,
    preparationTime: '25 min',
  },
  {
    id: '12',
    name: 'Spaghetti Bolognese',
    description: 'Traditional pasta with rich meat sauce',
    price: 17.99,
    image: 'food-12.png',
    category: 'Pasta',
    rating: 4.5,
    preparationTime: '28 min',
  },
  {
    id: '13',
    name: 'Beef Tacos',
    description: 'Three soft tacos with seasoned ground beef',
    price: 14.99,
    image: 'food-13.png',
    category: 'Mexican',
    rating: 4.4,
    preparationTime: '15 min',
  },
  {
    id: '14',
    name: 'Mushroom Risotto',
    description: 'Creamy risotto with wild mushrooms',
    price: 19.99,
    image: 'food-14.png',
    category: 'Italian',
    rating: 4.6,
    preparationTime: '30 min',
  },
  {
    id: '15',
    name: 'Thai Green Curry',
    description: 'Spicy curry with coconut milk and vegetables',
    price: 16.99,
    image: 'food-15.png',
    category: 'Thai',
    rating: 4.5,
    preparationTime: '22 min',
  },
  {
    id: '16',
    name: 'Club Sandwich',
    description: 'Triple-decker sandwich with turkey and bacon',
    price: 12.99,
    image: 'food-16.png',
    category: 'Sandwiches',
    rating: 4.2,
    preparationTime: '12 min',
  },
  {
    id: '17',
    name: 'Lobster Roll',
    description: 'Fresh lobster meat in a buttered roll',
    price: 28.99,
    image: 'food-17.png',
    category: 'Seafood',
    rating: 4.9,
    isPopular: true,
    preparationTime: '15 min',
  },
  {
    id: '18',
    name: 'Chicken Quesadilla',
    description: 'Grilled tortilla with chicken and cheese',
    price: 13.99,
    image: 'food-18.png',
    category: 'Mexican',
    rating: 4.3,
    preparationTime: '14 min',
  },
  {
    id: '19',
    name: 'Beef Stir Fry',
    description: 'Tender beef with mixed vegetables',
    price: 18.99,
    image: 'food-19.png',
    category: 'Asian',
    rating: 4.4,
    preparationTime: '20 min',
  },
  {
    id: '20',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes and basil',
    price: 13.99,
    image: 'food-20.png',
    category: 'Salads',
    rating: 4.3,
    preparationTime: '10 min',
  },
  {
    id: '21',
    name: 'Pork Chops',
    description: 'Grilled pork chops with apple sauce',
    price: 21.99,
    image: 'food-21.png',
    category: 'Pork',
    rating: 4.5,
    preparationTime: '25 min',
  },
  {
    id: '22',
    name: 'Vegetable Curry',
    description: 'Mixed vegetables in aromatic curry sauce',
    price: 15.99,
    image: 'food-22.png',
    category: 'Vegetarian',
    rating: 4.2,
    preparationTime: '20 min',
  },
  {
    id: '23',
    name: 'Fish Tacos',
    description: 'Grilled fish with cabbage slaw and lime',
    price: 16.99,
    image: 'food-23.png',
    category: 'Mexican',
    rating: 4.6,
    preparationTime: '18 min',
  },
  {
    id: '24',
    name: 'Chicken Parmesan',
    description: 'Breaded chicken with marinara and cheese',
    price: 19.99,
    image: 'food-24.png',
    category: 'Italian',
    rating: 4.7,
    isPopular: true,
    preparationTime: '28 min',
  },
  {
    id: '25',
    name: 'Beef Burrito',
    description: 'Large burrito with seasoned beef and beans',
    price: 14.99,
    image: 'food-25.png',
    category: 'Mexican',
    rating: 4.4,
    preparationTime: '16 min',
  },
  {
    id: '26',
    name: 'Shrimp Scampi',
    description: 'Garlic shrimp over linguine pasta',
    price: 22.99,
    image: 'food-26.png',
    category: 'Seafood',
    rating: 4.6,
    preparationTime: '22 min',
  },
  {
    id: '27',
    name: 'Chicken Tikka Masala',
    description: 'Creamy tomato curry with tender chicken',
    price: 18.99,
    image: 'food-27.png',
    category: 'Indian',
    rating: 4.5,
    preparationTime: '25 min',
  },
  {
    id: '28',
    name: 'Veggie Burger',
    description: 'Plant-based burger with avocado',
    price: 13.99,
    image: 'food-28.png',
    category: 'Vegetarian',
    rating: 4.1,
    preparationTime: '15 min',
  },
  {
    id: '29',
    name: 'Lamb Gyro',
    description: 'Seasoned lamb in pita with tzatziki',
    price: 16.99,
    image: 'food-29.png',
    category: 'Greek',
    rating: 4.4,
    preparationTime: '18 min',
  },
  {
    id: '30',
    name: 'Pad Thai',
    description: 'Stir-fried noodles with shrimp and peanuts',
    price: 17.99,
    image: 'food-30.png',
    category: 'Thai',
    rating: 4.5,
    preparationTime: '20 min',
  },
  {
    id: '31',
    name: 'Steak Fajitas',
    description: 'Sizzling beef strips with peppers and onions',
    price: 23.99,
    image: 'food-31.png',
    category: 'Mexican',
    rating: 4.7,
    isPopular: true,
    preparationTime: '22 min',
  },
  {
    id: '32',
    name: 'Chicken Noodle Soup',
    description: 'Homestyle soup with tender chicken and noodles',
    price: 9.99,
    image: 'food-32.png',
    category: 'Soups',
    rating: 4.3,
    preparationTime: '15 min',
  },
  {
    id: '33',
    name: 'Tuna Poke Bowl',
    description: 'Fresh tuna with rice and vegetables',
    price: 19.99,
    image: 'food-33.png',
    category: 'Hawaiian',
    rating: 4.6,
    preparationTime: '12 min',
  },
  {
    id: '34',
    name: 'Chicken Caesar Wrap',
    description: 'Grilled chicken with caesar dressing in tortilla',
    price: 11.99,
    image: 'food-34.png',
    category: 'Wraps',
    rating: 4.2,
    preparationTime: '10 min',
  },
  {
    id: '35',
    name: 'Beef Ramen',
    description: 'Rich broth with beef and soft-boiled egg',
    price: 16.99,
    image: 'food-35.png',
    category: 'Japanese',
    rating: 4.5,
    preparationTime: '25 min',
  },
  {
    id: '36',
    name: 'Quinoa Salad',
    description: 'Healthy quinoa with mixed vegetables',
    price: 12.99,
    image: 'food-36.png',
    category: 'Healthy',
    rating: 4.1,
    preparationTime: '8 min',
  },
  {
    id: '37',
    name: 'Duck Confit',
    description: 'Slow-cooked duck leg with herbs',
    price: 26.99,
    image: 'food-37.png',
    category: 'French',
    rating: 4.8,
    isPopular: true,
    preparationTime: '35 min',
  },
  {
    id: '38',
    name: 'Chicken Shawarma',
    description: 'Marinated chicken with garlic sauce',
    price: 15.99,
    image: 'food-38.png',
    category: 'Middle Eastern',
    rating: 4.4,
    preparationTime: '18 min',
  },
  {
    id: '39',
    name: 'Vegetable Stir Fry',
    description: 'Fresh vegetables in savory sauce',
    price: 13.99,
    image: 'food-39.png',
    category: 'Vegetarian',
    rating: 4.2,
    preparationTime: '15 min',
  },
  {
    id: '40',
    name: 'Fish and Chips Deluxe',
    description: 'Beer-battered cod with thick-cut chips',
    price: 18.99,
    image: 'food-40.png',
    category: 'British',
    rating: 4.5,
    preparationTime: '20 min',
  },
  {
    id: '41',
    name: 'Korean BBQ Bowl',
    description: 'Marinated beef with kimchi and rice',
    price: 17.99,
    image: 'food-41.png',
    category: 'Korean',
    rating: 4.6,
    preparationTime: '22 min',
  },
  {
    id: '42',
    name: 'Chicken Enchiladas',
    description: 'Rolled tortillas with chicken and cheese sauce',
    price: 16.99,
    image: 'food-42.png',
    category: 'Mexican',
    rating: 4.4,
    preparationTime: '25 min',
  },
  {
    id: '43',
    name: 'Mediterranean Bowl',
    description: 'Hummus, falafel, and fresh vegetables',
    price: 14.99,
    image: 'food-43.png',
    category: 'Mediterranean',
    rating: 4.3,
    preparationTime: '12 min',
  },
  {
    id: '44',
    name: 'Pork Belly Bao',
    description: 'Steamed buns with braised pork belly',
    price: 15.99,
    image: 'food-44.png',
    category: 'Asian',
    rating: 4.5,
    preparationTime: '20 min',
  },
  {
    id: '45',
    name: 'Chicken Alfredo',
    description: 'Creamy pasta with grilled chicken',
    price: 18.99,
    image: 'food-45.png',
    category: 'Italian',
    rating: 4.4,
    preparationTime: '24 min',
  },
  {
    id: '46',
    name: 'Beef Pho',
    description: 'Vietnamese noodle soup with beef',
    price: 14.99,
    image: 'food-46.png',
    category: 'Vietnamese',
    rating: 4.6,
    preparationTime: '18 min',
  },
  {
    id: '47',
    name: 'Turkey Club Wrap',
    description: 'Sliced turkey with bacon in a wrap',
    price: 12.99,
    image: 'food-47.png',
    category: 'Wraps',
    rating: 4.2,
    preparationTime: '10 min',
  },
  {
    id: '48',
    name: 'Seafood Paella',
    description: 'Spanish rice dish with mixed seafood',
    price: 24.99,
    image: 'food-48.png',
    category: 'Spanish',
    rating: 4.7,
    isPopular: true,
    preparationTime: '30 min',
  },
  {
    id: '49',
    name: 'Chicken Teriyaki Bowl',
    description: 'Grilled chicken with teriyaki sauce over rice',
    price: 15.99,
    image: 'food-49.png',
    category: 'Japanese',
    rating: 4.3,
    preparationTime: '18 min',
  },
  {
    id: '50',
    name: 'Veggie Pizza',
    description: 'Pizza topped with fresh vegetables',
    price: 17.99,
    image: 'food-50.png',
    category: 'Pizza',
    rating: 4.2,
    preparationTime: '22 min',
  },
  {
    id: '51',
    name: 'Beef Stroganoff',
    description: 'Tender beef in creamy mushroom sauce',
    price: 20.99,
    image: 'food-51.png',
    category: 'Russian',
    rating: 4.5,
    preparationTime: '28 min',
  },
  {
    id: '52',
    name: 'Chicken Satay',
    description: 'Grilled chicken skewers with peanut sauce',
    price: 14.99,
    image: 'food-52.png',
    category: 'Thai',
    rating: 4.4,
    preparationTime: '16 min',
  },
  {
    id: '53',
    name: 'Fish Curry',
    description: 'Spicy fish curry with coconut milk',
    price: 18.99,
    image: 'food-53.png',
    category: 'Indian',
    rating: 4.5,
    preparationTime: '25 min',
  },
  {
    id: '54',
    name: 'Pulled Pork Sandwich',
    description: 'Slow-cooked pork with BBQ sauce',
    price: 13.99,
    image: 'food-54.png',
    category: 'BBQ',
    rating: 4.6,
    preparationTime: '15 min',
  },
  {
    id: '55',
    name: 'Chicken Biryani',
    description: 'Fragrant rice with spiced chicken',
    price: 17.99,
    image: 'food-55.png',
    category: 'Indian',
    rating: 4.7,
    isPopular: true,
    preparationTime: '30 min',
  },
  {
    id: '56',
    name: 'Grilled Portobello',
    description: 'Marinated portobello mushroom burger',
    price: 12.99,
    image: 'food-56.png',
    category: 'Vegetarian',
    rating: 4.1,
    preparationTime: '14 min',
  },
];
